FROM node:alpine

# Working directory
WORKDIR '/app/frontend'

# Copy all local files into the image.
COPY . .

RUN npm install
RUN npm audit fix

EXPOSE 3000

# Set the command to start the node server.
CMD npm start
